//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookRecod
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string author_name { get; set; }
        public string category { get; set; }
        public int copies { get; set; }
    }
}
