//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeRecord
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_email { get; set; }
        public string emp_phone { get; set; }
        public string emp_pass { get; set; }
        public string emp_add { get; set; }
        public string role { get; set; }
        public string username { get; set; }
    }
}
