//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_Management_SystemEntities : DbContext
    {
        public Library_Management_SystemEntities()
            : base("name=Library_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookRecod> bookRecod { get; set; }
        public virtual DbSet<employeeRecord> employeeRecord { get; set; }
        public virtual DbSet<memberRecord> memberRecord { get; set; }
        public virtual DbSet<transactionRecord> transactionRecord { get; set; }
    }
}
