//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionRecord
    {
        public int trans_id { get; set; }
        public int emp_id { get; set; }
        public int book_id { get; set; }
        public int mem_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime return_date { get; set; }
        public System.DateTime last_date { get; set; }
        public string penalty { get; set; }
    }
}
